import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { z } from "zod";

import { summarizeBanRisk } from "@/lib/jobs/ban-risk";
import { isMockMode } from "@/lib/integrations/mode";
import { pickBestVariant, scoreVariant } from "@/lib/jobs/scoring";

const codexVariantSchema = z.object({
  variant_no: z.number().int().positive(),
  title: z.string().min(1),
  body_html: z.string().min(1),
  meta_description: z.string().min(1),
  thumbnail_prompt: z.string().min(1),
  source_count: z.number().int().nonnegative(),
});

const codexCraftResultSchema = z.object({
  variants: z.array(codexVariantSchema).length(4),
  selected_variant_no: z.number().int().positive(),
  best_angle: z.string().min(1),
  why_best: z.string().min(1),
  ban_risk_summary: z.string().min(1),
});

const craftVariantSchema = z.object({
  variantNo: z.number().int().positive(),
  title: z.string().min(1),
  body: z.string().min(1),
  metaDescription: z.string().min(1),
  thumbnailPrompt: z.string().min(1),
  sourceCount: z.number().int().nonnegative(),
});

const craftResultSchema = z.object({
  variants: z.array(craftVariantSchema).length(4),
  selectedVariantNo: z.number().int().positive(),
  bestAngle: z.string().min(1),
  whyBest: z.string().min(1),
  banRiskSummary: z.string().min(1),
});

export type CraftResult = z.infer<typeof craftResultSchema>;

function toHeadline(coinSlug: string, variantNo: number) {
  const readable = coinSlug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

  const headlines = [
    `${readable} Draws Attention as Traders Watch the Next Catalyst`,
    `${readable} Builds a Clearer Narrative as Investors Look for Stronger Signals`,
    `${readable} Gains Fresh Interest as Market Attention Turns to Structure and Utility`,
  ];

  return headlines[variantNo - 1] ?? headlines[0];
}

function toBody(coinSlug: string, variantNo: number) {
  const readable = coinSlug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

  const angles = [
    "market attention and visible catalysts",
    "clearer positioning and project narrative",
    "utility, structure, and what users should watch next",
  ];

  return `<p>${readable} is being evaluated through the lens of ${
    angles[variantNo - 1] ?? angles[0]
  }.</p><p>This draft is a placeholder craft result for the dashboard MVP. Replace the adapter with the full top-cmc-writer orchestration to generate production-grade article research, source-backed analysis, and platform-safe copy.</p><p>For the current MVP, the worker produces three variants, scores them, and selects the strongest option for publishing workflow tests. The final production integration should preserve non-CMC sourcing rules, ban-risk checks, and CoinMarketCap-safe tone controls.</p>`;
}

function toMetaDescription(coinSlug: string, variantNo: number) {
  return `${coinSlug} variant ${variantNo} draft generated by the CMC author dashboard MVP workflow.`;
}

function toThumbnailPrompt(coinSlug: string, variantNo: number) {
  return `Create a premium editorial crypto thumbnail for ${coinSlug}, variant ${variantNo}, with clean negative space for headline text and a confident market-news visual tone.`;
}

function toMockResult(coinSlug: string): CraftResult {
  const variants = [1, 2, 3, 4].map((variantNo) => ({
    variantNo,
    title: toHeadline(coinSlug, variantNo),
    body: toBody(coinSlug, variantNo),
    metaDescription: toMetaDescription(coinSlug, variantNo),
    thumbnailPrompt: toThumbnailPrompt(coinSlug, variantNo),
    sourceCount: 2,
  }));

  const selected = pickBestVariant(variants);
  const selectedVariant = selected?.variant ?? variants[0];
  const score = scoreVariant(selectedVariant);

  return {
    variants,
    selectedVariantNo: selectedVariant.variantNo,
    bestAngle: "Mock-mode highest-score variant from the craft adapter",
    whyBest: `Selected for strongest combined score (${score.total}) across hook, structure, and publish readiness in mock mode.`,
    banRiskSummary: summarizeBanRisk({
      title: selectedVariant.title,
      body: selectedVariant.body,
      sourceCount: selectedVariant.sourceCount,
    }),
  };
}

function buildCodexPrompt(cmcUrl: string, coinSlug: string) {
  return [
    "Use the top-cmc-writer skill for this task.",
    "You are writing for the CMC Author Dashboard craft pipeline.",
    "Analyze the provided CoinMarketCap coin page URL the same way an operator would in Codex.",
    "Use only non-CoinMarketCap sources for factual support in the article output.",
    "Do not include any source URL, citation, or hyperlink containing the string coinmarketcap anywhere in body_html.",
    "Do not default to bearish, negative, bullish, or promotional framing. Optimize for pattern-fit, source strength, and publish safety.",
    "Return exactly four variants.",
    "Every variant body_html must be ready to paste directly into WordPress.",
    "Keep the output publish-safe and compliant with CoinMarketCap community rules.",
    `Coin slug: ${coinSlug}`,
    `Coin page URL: ${cmcUrl}`,
  ].join("\n");
}

function buildOutputSchema() {
  return {
    type: "object",
    additionalProperties: false,
    properties: {
      variants: {
        type: "array",
        minItems: 4,
        maxItems: 4,
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            variant_no: { type: "integer" },
            title: { type: "string" },
            body_html: { type: "string" },
            meta_description: { type: "string" },
            thumbnail_prompt: { type: "string" },
            source_count: { type: "integer" },
          },
          required: [
            "variant_no",
            "title",
            "body_html",
            "meta_description",
            "thumbnail_prompt",
            "source_count",
          ],
        },
      },
      selected_variant_no: { type: "integer" },
      best_angle: { type: "string" },
      why_best: { type: "string" },
      ban_risk_summary: { type: "string" },
    },
    required: [
      "variants",
      "selected_variant_no",
      "best_angle",
      "why_best",
      "ban_risk_summary",
    ],
  };
}

function toInternalCraftResult(raw: z.infer<typeof codexCraftResultSchema>): CraftResult {
  const parsed = craftResultSchema.parse({
    variants: raw.variants.map((variant) => ({
      variantNo: variant.variant_no,
      title: variant.title,
      body: variant.body_html,
      metaDescription: variant.meta_description,
      thumbnailPrompt: variant.thumbnail_prompt,
      sourceCount: variant.source_count,
    })),
    selectedVariantNo: raw.selected_variant_no,
    bestAngle: raw.best_angle,
    whyBest: raw.why_best,
    banRiskSummary: raw.ban_risk_summary,
  });

  for (const variant of parsed.variants) {
    if (variant.body.toLowerCase().includes("coinmarketcap")) {
      throw new Error("coinmarketcap URLs are not allowed in article output");
    }
  }

  return parsed;
}

async function craftLiveWithCodexExec(cmcUrl: string, coinSlug: string): Promise<CraftResult> {
  const codexBin = process.env.CODEX_BIN?.trim() || "codex";
  const model = process.env.CRAFT_MODEL?.trim() || process.env.OPENAI_MODEL?.trim();
  const tempDir = await mkdtemp(path.join(tmpdir(), "cmc-author-dashboard-"));
  const schemaPath = path.join(tempDir, "craft-schema.json");
  const outputPath = path.join(tempDir, "craft-output.json");

  try {
    await writeFile(schemaPath, JSON.stringify(buildOutputSchema(), null, 2), "utf8");

    const args = [
      "exec",
      "--dangerously-bypass-approvals-and-sandbox",
      "--skip-git-repo-check",
      "--output-last-message",
      outputPath,
      "--output-schema",
      schemaPath,
    ];

    if (model) {
      args.push("--model", model);
    }

    args.push(buildCodexPrompt(cmcUrl, coinSlug));

    const stdout = await new Promise<string>((resolve, reject) => {
      execFile(
        codexBin,
        args,
        {
          cwd: process.cwd(),
          maxBuffer: 10 * 1024 * 1024,
        },
        (error, commandStdout) => {
          if (error) {
            reject(error);
            return;
          }

          resolve(commandStdout);
        },
      );
    });

    let rawOutput = "";

    try {
      rawOutput = await readFile(outputPath, "utf8");
    } catch {
      rawOutput = stdout;
    }

    if (!rawOutput.trim()) {
      throw new Error("Codex did not produce a craft result.");
    }

    const parsed = codexCraftResultSchema.parse(JSON.parse(rawOutput));
    return toInternalCraftResult(parsed);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown codex craft error.";
    throw new Error(`Codex craft execution failed: ${message}`);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

export async function craftFromCoinPage(cmcUrl: string, coinSlug: string): Promise<CraftResult> {
  if (isMockMode()) {
    return toMockResult(coinSlug);
  }

  return craftLiveWithCodexExec(cmcUrl, coinSlug);
}
