import { z } from "zod";

import { summarizeBanRisk } from "@/lib/jobs/ban-risk";
import { isMockMode, requireLiveEnv } from "@/lib/integrations/mode";
import { pickBestVariant, scoreVariant } from "@/lib/jobs/scoring";

const craftVariantSchema = z.object({
  variantNo: z.number().int().positive(),
  title: z.string().min(1),
  body: z.string().min(1),
  metaDescription: z.string().min(1),
  thumbnailPrompt: z.string().min(1),
  sourceCount: z.number().int().nonnegative(),
});

const craftResultSchema = z.object({
  variants: z.array(craftVariantSchema).length(3),
  selectedVariantNo: z.number().int().positive(),
  bestAngle: z.string().min(1),
  whyBest: z.string().min(1),
  banRiskSummary: z.string().min(1),
});

export type CraftResult = z.infer<typeof craftResultSchema>;

type OpenAIResponsesPayload = {
  output?: Array<{
    content?: Array<{
      text?: string;
      type?: string;
    }>;
    type?: string;
  }>;
  output_text?: string;
};

function toHeadline(coinSlug: string, variantNo: number) {
  const readable = coinSlug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

  const headlines = [
    `${readable} Draws Attention as Traders Watch the Next Catalyst`,
    `${readable} Builds a Clearer Narrative as Investors Look for Stronger Signals`,
    `${readable} Gains Fresh Interest as Market Attention Turns to Structure and Utility`,
  ];

  return headlines[variantNo - 1] ?? headlines[0];
}

function toBody(coinSlug: string, variantNo: number) {
  const readable = coinSlug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

  const angles = [
    "market attention and visible catalysts",
    "clearer positioning and project narrative",
    "utility, structure, and what users should watch next",
  ];

  return `${readable} is being evaluated through the lens of ${angles[variantNo - 1] ?? angles[0]}. This draft is a placeholder craft result for the dashboard MVP. Replace the adapter with the full top-cmc-writer orchestration to generate production-grade article research, source-backed analysis, and platform-safe copy.\n\nFor the current MVP, the worker produces three variants, scores them, and selects the strongest option for publishing workflow tests. The final production integration should preserve non-CMC sourcing rules, ban-risk checks, and CoinMarketCap-safe tone controls.`;
}

function toMetaDescription(coinSlug: string, variantNo: number) {
  return `${coinSlug} variant ${variantNo} draft generated by the CMC author dashboard MVP workflow.`;
}

function toThumbnailPrompt(coinSlug: string, variantNo: number) {
  return `Create a premium editorial crypto thumbnail for ${coinSlug}, variant ${variantNo}, with clean negative space for headline text and a confident market-news visual tone.`;
}

function toMockResult(coinSlug: string): CraftResult {
  const variants = [1, 2, 3].map((variantNo) => ({
    variantNo,
    title: toHeadline(coinSlug, variantNo),
    body: toBody(coinSlug, variantNo),
    metaDescription: toMetaDescription(coinSlug, variantNo),
    thumbnailPrompt: toThumbnailPrompt(coinSlug, variantNo),
    sourceCount: 2,
  }));

  const selected = pickBestVariant(variants);
  const selectedVariant = selected?.variant ?? variants[0];
  const score = scoreVariant(selectedVariant);

  return {
    variants,
    selectedVariantNo: selectedVariant.variantNo,
    bestAngle: "Mock-mode highest-score variant from the craft adapter",
    whyBest: `Selected for strongest combined score (${score.total}) across hook, structure, and publish readiness in mock mode.`,
    banRiskSummary: summarizeBanRisk({
      title: selectedVariant.title,
      body: selectedVariant.body,
      sourceCount: selectedVariant.sourceCount,
    }),
  };
}

function extractOutputText(payload: OpenAIResponsesPayload) {
  if (typeof payload.output_text === "string" && payload.output_text.trim().length > 0) {
    return payload.output_text;
  }

  for (const item of payload.output ?? []) {
    for (const content of item.content ?? []) {
      if (content.type === "output_text" && typeof content.text === "string") {
        return content.text;
      }
    }
  }

  throw new Error("OpenAI craft response did not include structured output text.");
}

function buildLivePrompt(cmcUrl: string, coinSlug: string) {
  return [
    "You are the top-cmc-writer integration for an internal editorial dashboard.",
    "Research and draft with only non-CoinMarketCap factual sources.",
    "You may inspect the provided CoinMarketCap coin page URL for context, but do not cite CoinMarketCap, CMC community content, or CMC AI output as factual sources.",
    "Return exactly three article variants and choose the best one.",
    "Each variant must include variantNo, title, body, metaDescription, thumbnailPrompt, and sourceCount.",
    "Keep tone publish-safe, non-manipulative, and compliant with CoinMarketCap community rules.",
    `Coin slug: ${coinSlug}`,
    `Coin page URL: ${cmcUrl}`,
  ].join("\n");
}

async function craftLiveFromOpenAI(cmcUrl: string, coinSlug: string): Promise<CraftResult> {
  const apiKey = requireLiveEnv("OPENAI_API_KEY", process.env.OPENAI_API_KEY);
  const model =
    process.env.CRAFT_MODEL?.trim() || process.env.OPENAI_MODEL?.trim() || "gpt-5.4-mini";

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      input: buildLivePrompt(cmcUrl, coinSlug),
      text: {
        format: {
          type: "json_schema",
          name: "cmc_author_dashboard_craft_result",
          schema: {
            type: "object",
            additionalProperties: false,
            properties: {
              variants: {
                type: "array",
                minItems: 3,
                maxItems: 3,
                items: {
                  type: "object",
                  additionalProperties: false,
                  properties: {
                    variantNo: { type: "integer" },
                    title: { type: "string" },
                    body: { type: "string" },
                    metaDescription: { type: "string" },
                    thumbnailPrompt: { type: "string" },
                    sourceCount: { type: "integer" },
                  },
                  required: [
                    "variantNo",
                    "title",
                    "body",
                    "metaDescription",
                    "thumbnailPrompt",
                    "sourceCount",
                  ],
                },
              },
              selectedVariantNo: { type: "integer" },
              bestAngle: { type: "string" },
              whyBest: { type: "string" },
              banRiskSummary: { type: "string" },
            },
            required: [
              "variants",
              "selectedVariantNo",
              "bestAngle",
              "whyBest",
              "banRiskSummary",
            ],
          },
        },
      },
      tools: [{ type: "web_search_preview" }],
    }),
  });

  if (!response.ok) {
    throw new Error(`OpenAI craft request failed with status ${response.status}.`);
  }

  const payload = (await response.json()) as OpenAIResponsesPayload;
  const parsed = JSON.parse(extractOutputText(payload));
  return craftResultSchema.parse(parsed);
}

export async function craftFromCoinPage(cmcUrl: string, coinSlug: string): Promise<CraftResult> {
  if (isMockMode()) {
    return toMockResult(coinSlug);
  }

  return craftLiveFromOpenAI(cmcUrl, coinSlug);
}
